import pygame
from math import sqrt, ceil


PATH = 'audio/piano0.3/*.wav'
SAMPLE_RATE = 22050

SCREEN_WIDTH = 1500
SCREEN_HEIGHT = 800

LEFT_MARGIN = 100
RIGHT_MARGIN = LEFT_MARGIN
TOP_MARGIN = 30
BOTTOM_MARGIN = TOP_MARGIN

MAX_FIELD_WIDTH = SCREEN_WIDTH - LEFT_MARGIN - RIGHT_MARGIN
MAX_FIELD_HEIGHT = 500

OUTPUT_LENGTH = 15
TILES_COUNT = 24

TILE_GAP = 1
BLOCK_GAP = min(max(70 // OUTPUT_LENGTH, 1), 10)

BLOCK_WIDTH = MAX_FIELD_WIDTH // OUTPUT_LENGTH
FIELD_WIDTH = BLOCK_WIDTH * OUTPUT_LENGTH

TILES_COUNT_IN_ROW = ceil(sqrt(TILES_COUNT))

TILE_WIDTH = int(((MAX_FIELD_WIDTH - BLOCK_GAP * (OUTPUT_LENGTH - 1)) / OUTPUT_LENGTH + TILE_GAP) / TILES_COUNT_IN_ROW - TILE_GAP)
TILE_HEIGHT = TILE_WIDTH

BLOCK_WIDTH = TILES_COUNT_IN_ROW * (TILE_WIDTH + TILE_GAP) - TILE_GAP
BLOCK_HEIGHT = TILES_COUNT_IN_ROW * (TILE_HEIGHT + TILE_GAP) - TILE_GAP

FIELD_WIDTH = BLOCK_WIDTH * OUTPUT_LENGTH + BLOCK_GAP * (OUTPUT_LENGTH - 1)
FIELD_HEIGHT = BLOCK_HEIGHT

SIDE_PAD = 30
TOP_PAD = 30

BLACK = 0, 0, 0
WHITE = 255, 255, 255
DARK_GREY = 64, 64, 64
BUTTON_COLORS = ((200, 200, 200), (170, 170, 170), (150, 150, 150))

pygame.font.init()
FONT = pygame.font.SysFont(None, 30)

BUTTON_WIDTH = 150
BUTTON_HEIGHT = 40

COLLAPSE_BUTTON_POS = ((SCREEN_WIDTH-BUTTON_WIDTH) // 2 - BUTTON_WIDTH - 15, SCREEN_HEIGHT-BUTTON_HEIGHT-25)
RENOVATE_BUTTON_POS = ((SCREEN_WIDTH-BUTTON_WIDTH) // 2, SCREEN_HEIGHT-BUTTON_HEIGHT-25)
SAVE_BUTTON_POS = ((SCREEN_WIDTH-BUTTON_WIDTH) // 2 + BUTTON_WIDTH + 15, SCREEN_HEIGHT-BUTTON_HEIGHT-25)
RENDER_MODE_BUTTON_POS = ((SCREEN_WIDTH-BUTTON_WIDTH) // 2 + 2 * BUTTON_WIDTH + 50, SCREEN_HEIGHT-BUTTON_HEIGHT-25)
COLLAPSE_MODE_BUTTON_POS = ((SCREEN_WIDTH-BUTTON_WIDTH) // 2 + 2 * BUTTON_WIDTH + 15, SCREEN_HEIGHT-BUTTON_HEIGHT-25)

LEFT = 1

FPS = 60

FRAME_SIZE = 2048
HOP_SIZE = 512
FILTERS_COUNT = 100
